language: python
python:
  - "3.5.2"
before_install:
  - pip install -U pip
  - python setup.py install
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest