language: python
python:
  - "3.5.2"
install:
  - 'pip install pipenv pytest'
  - 'pipenv install'
script: 'python -m pytest --cov=pyblizzard tests --cov-report=xml'
after_success:
  - 'python-codacy-coverage -r coverage.xml'  