language: python
python:
  - "3.5.2"
before_install:
  - pip install -U pip
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install pipenv pytest
  - pipenv install
script:
  - pytest
after_success:
  - python-codacy-coverage -r coverage.xml